# vx01_controller_manager_hw.yaml
# Same as sim version but use_sim_time: false and no drone_arm_controller

controller_manager:
  ros__parameters:
    update_rate: 50          # 50 Hz â€” Maestro serial is too slow for 1000 Hz
    use_sim_time: false

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    leg_0_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    leg_1_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    leg_2_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    leg_3_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    leg_4_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    leg_5_controller:
      type: joint_trajectory_controller/JointTrajectoryController


joint_state_broadcaster:
  ros__parameters:
    use_sim_time: false


leg_0_controller:
  ros__parameters:
    use_sim_time: false
    joints: [coxa_leg0_joint, femur_leg0_joint, tibia_leg0_joint]
    command_interfaces: [position]
    state_interfaces:   [position]
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 0.0
      coxa_leg0_joint:  { trajectory: 1.0, goal: 0.8 }
      femur_leg0_joint: { trajectory: 1.0, goal: 0.8 }
      tibia_leg0_joint: { trajectory: 1.0, goal: 0.8 }

leg_1_controller:
  ros__parameters:
    use_sim_time: false
    joints: [coxa_leg1_joint, femur_leg1_joint, tibia_leg1_joint]
    command_interfaces: [position]
    state_interfaces:   [position]
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 0.0
      coxa_leg1_joint:  { trajectory: 1.0, goal: 0.8 }
      femur_leg1_joint: { trajectory: 1.0, goal: 0.8 }
      tibia_leg1_joint: { trajectory: 1.0, goal: 0.8 }

leg_2_controller:
  ros__parameters:
    use_sim_time: false
    joints: [coxa_leg2_joint, femur_leg2_joint, tibia_leg2_joint]
    command_interfaces: [position]
    state_interfaces:   [position]
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 0.0
      coxa_leg2_joint:  { trajectory: 1.0, goal: 0.8 }
      femur_leg2_joint: { trajectory: 1.0, goal: 0.8 }
      tibia_leg2_joint: { trajectory: 1.0, goal: 0.8 }

leg_3_controller:
  ros__parameters:
    use_sim_time: false
    joints: [coxa_leg3_joint, femur_leg3_joint, tibia_leg3_joint]
    command_interfaces: [position]
    state_interfaces:   [position]
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 0.0
      coxa_leg3_joint:  { trajectory: 1.0, goal: 0.8 }
      femur_leg3_joint: { trajectory: 1.0, goal: 0.8 }
      tibia_leg3_joint: { trajectory: 1.0, goal: 0.8 }

leg_4_controller:
  ros__parameters:
    use_sim_time: false
    joints: [coxa_leg4_joint, femur_leg4_joint, tibia_leg4_joint]
    command_interfaces: [position]
    state_interfaces:   [position]
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 0.0
      coxa_leg4_joint:  { trajectory: 1.0, goal: 0.8 }
      femur_leg4_joint: { trajectory: 1.0, goal: 0.8 }
      tibia_leg4_joint: { trajectory: 1.0, goal: 0.8 }

leg_5_controller:
  ros__parameters:
    use_sim_time: false
    joints: [coxa_leg5_joint, femur_leg5_joint, tibia_leg5_joint]
    command_interfaces: [position]
    state_interfaces:   [position]
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 0.0
      coxa_leg5_joint:  { trajectory: 1.0, goal: 0.8 }
      femur_leg5_joint: { trajectory: 1.0, goal: 0.8 }
      tibia_leg5_joint: { trajectory: 1.0, goal: 0.8 }