joint_limits:

  # LEG 0
  coxa_leg0_joint:
    has_position_limits: true
    min_position: -0.785398   
    max_position: 0.785398    
    has_velocity_limits: true
    max_velocity: 3.14159     
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  femur_leg0_joint:
    has_position_limits: true
    min_position: -0.785398
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  tibia_leg0_joint:
    has_position_limits: true
    min_position: -0.785398   
    max_position: 0.785398          
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  # LEG 1
  coxa_leg1_joint:
    has_position_limits: true
    min_position: -0.785398
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  femur_leg1_joint:
    has_position_limits: true
    min_position: -0.785398
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  tibia_leg1_joint:
    has_position_limits: true
    min_position: -0.785398
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  # LEG 2
  coxa_leg2_joint:
    has_position_limits: true
    min_position: -0.785398
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  femur_leg2_joint:
    has_position_limits: true
    min_position: -0.785398
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  tibia_leg2_joint:
    has_position_limits: true
    min_position: -0.785398
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  # LEG 3
  coxa_leg3_joint:
    has_position_limits: true
    min_position: -0.785398
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  femur_leg3_joint:
    has_position_limits: true
    min_position: -0.785398
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  tibia_leg3_joint:
    has_position_limits: true
    min_position: -0.785398
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  # LEG 4
  coxa_leg4_joint:
    has_position_limits: true
    min_position: -0.785398
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  femur_leg4_joint:
    has_position_limits: true
    min_position: -0.785398
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  tibia_leg4_joint:
    has_position_limits: true
    min_position: -0.785398
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  # LEG 5
  coxa_leg5_joint:
    has_position_limits: true
    min_position: -0.785398
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  femur_leg5_joint:
    has_position_limits: true
    min_position: -0.785398
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false

  tibia_leg5_joint:
    has_position_limits: true
    min_position: -0.785398
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false