controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Controllers to load
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    drone_arm_controller:
      type: forward_command_controller/ForwardCommandController

# Joint State Broadcaster
joint_state_broadcaster:
  ros__parameters:
    joints:
      - arm_joint0
      - arm_joint1
      - arm_joint2
      - arm_joint3

# Arm servo position controller
drone_arm_controller:
  ros__parameters:
    joints:
      - arm_joint0
      - arm_joint1
      - arm_joint2
      - arm_joint3
    interface_name: position