joint_limits:

  # ARM SERVO JOINTS
  # Roll axis (X-axis)
  # GPIO PWM on RDK X5

  drone_arm0_joint:
    has_position_limits: true
    min_position: -1.5707963    
    max_position: 1.5707963     
    has_velocity_limits: true
    max_velocity: 1.5707963     
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: false

  drone_arm1_joint:
    has_position_limits: true
    min_position: -1.5707963
    max_position: 1.5707963
    has_velocity_limits: true
    max_velocity: 1.5707963
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: false

  drone_arm2_joint:
    has_position_limits: true
    min_position: -1.5707963
    max_position: 1.5707963
    has_velocity_limits: true
    max_velocity: 1.5707963
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: false

  drone_arm3_joint:
    has_position_limits: true
    min_position: -1.5707963
    max_position: 1.5707963
    has_velocity_limits: true
    max_velocity: 1.5707963
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: false