controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Controllers to load
    drone_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    drone_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Joint State Broadcaster
drone_joint_state_broadcaster:
  ros__parameters:
    joints:
      - arm_joint0
      - arm_joint1
      - arm_joint2
      - arm_joint3

# Arm servo position controller
drone_arm_controller:
  ros__parameters:
    joints:
      - arm_joint0
      - arm_joint1
      - arm_joint2
      - arm_joint3
    
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity